name = "CherryMoonlight"
author = "OoLunar"
version = "1.27.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4aadc2486fd760253b516620e5dc88f9557d69c10fe85836c727f4dfd38c912"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
