name = "CherryMoonlight"
author = "OoLunar"
version = "1.30.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6584ce70733c2aa1c9db7522514c3da7204a2950d0633babcd587d29d3553dcb"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
