name = "CherryMoonlight"
author = "OoLunar"
version = "1.27.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba221e5f920c411e3057f9bdc142c8811264c02f2273777115bc09db8444bcd2"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
