name: Publish Modpack

on:
  push:
    paths:
      - "src/**"
    branches:
      - master
  schedule:
    # Once every week
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install .NET
        uses: actions/setup-dotnet@main
      - name: Update The Modpack
        id: push
        run: |
          # Install Packwiz
          go install github.com/packwiz/packwiz@latest

          # Make it available to everyone
          export PATH="$HOME/go/bin:$PATH"

          # Update the modpack
          dotnet run --project ${{ github.workspace }}/tools/OoLunar.CherryMoonlight.Tools.Updater/CherryMoonlight.csproj

          # Go into the modpack directory
          cd ${{ github.workspace }}/src

          # Parse the modpack version
          MODPACK_VERSION="$(grep -Po 'version = "\K[^"]+' pack.toml)"
          echo MODPACK_VERSION="$MODPACK_VERSION" >> $GITHUB_OUTPUT

          # Parse the game version
          GAME_VERSION="$(grep -Po 'minecraft = "\K[^"]+' pack.toml)"
          echo "GAME_VERSION=$GAME_VERSION" >> $GITHUB_OUTPUT

          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            # Identify as GitHub Actions
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"

            # Commit changes
            git add .
            git commit -m "Update to $MODPACK_VERSION"

            # Create a new tag
            git tag -a "$MODPACK_VERSION" -m "Update to $MODPACK_VERSION"

            # Push changes
            git push
          fi

          # Move the modpack to the root
          mv "CherryMoonlight-$MODPACK_VERSION.mrpack" ${{ github.workspace }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
            name: "CherryMoonlight-${{ steps.push.outputs.MODPACK_VERSION }}.mrpack"
            path: "CherryMoonlight-${{ steps.push.outputs.MODPACK_VERSION }}.mrpack"
      - uses: Kir-Antipov/mc-publish@v3
        with:
          changelog-file: "CHANGELOG.md"
          files: "*.mrpack"
          game-versions: ${{ steps.push.outputs.GAME_VERSION }}
          github-tag: ${{ steps.push.outputs.MODPACK_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          loaders: forge
          name: "Cherry Moonlight ${{ steps.push.outputs.MODPACK_VERSION }}"
          version-type: release
          version: ${{ steps.push.outputs.MODPACK_VERSION }}
          #modrinth-id: null
          #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}